### ISSUE TITLE
SyntaxError: Invalid flags supplied to RegExp constructor '^Release: #{semver}$'

### ISSUE THREAD

**Issue by cyberpwnn** [CupOfTea696/gh-action-auto-release#1]
```/home/runner/work/_actions/CupOfTea696/gh-action-auto-release/v1.0.0/dist/main.js:2
(()=>{var e={5265:function(e,t,r){"use strict";var n=this&&this.__importStar||function(e){if(e&&e.__esModule)return e;var t={};if(null!=e)for(var r in e)Object.hasOwnProperty.call(e,r)&&(t[r]=e[r]);return t.default=e,t};Object.defineProperty(t,"__esModule",{value:!0});const o=n(r(2087)),s=r(4570);function i(e,t,r){const n=new a(e,t,r);process.stdout.write(n.toString()+o.EOL)}t.issueCommand=i,t.issue=function(e,t=""){i(e,{},t)};class a{constructor(e,t,r){e||(e="missing.command"),this.command=e,this.properties=t,this.message=r}toString(){let e="::"+this.command;if(this.properties&&Object.keys(this.properties).length>0){e+=" ";let r=!0;for(const n in this.properties)if(this.properties.hasOwnProperty(n)){const o=this.properties[n];o&&(r?r=!1:e+=",",e+=`${n}=${t=o,s.toCommandValue(t).replace(/%/g,"%25").replace(/\r/g,"%0D").replace(/\n/g,"%0A").replace(/:/g,"%3A").replace(/,/g,"%2C")}`)}}var t;return e+=`::${function(e){return s.

SyntaxError: Invalid flags supplied to RegExp constructor '^Release: #{semver}$'
    at new RegExp (<anonymous>)
    at new <anonymous> (/home/runner/work/_actions/CupOfTea696/gh-action-auto-release/v1.0.0/dist/main.js:2:245617)
    at /home/runner/work/_actions/CupOfTea696/gh-action-auto-release/v1.0.0/dist/main.js:2:245009
    at /home/runner/work/_actions/CupOfTea696/gh-action-auto-release/v1.0.0/dist/main.js:2:249014
    at Object.<anonymous> (/home/runner/work/_actions/CupOfTea696/gh-action-auto-release/v1.0.0/dist/main.js:2:249018)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)```

**Comment by IvesCostaBr** [comment]
cc

**Comment by alkincakiralar1996** [comment]
++

**Comment by yankikucuk** [comment]
++

**Comment by tanishqmanuja** [comment]
update to latest release 1.0.2 in workflow yaml file

**Comment by Alfagun74** [comment]
Someone should close this issue and update the Examples with the 1.0.2 action.
